### ISSUE TITLE
Rest Support

### ISSUE THREAD

**Issue by briankboyd** [ryyaan2004/jcobrachat#3]
If we are going to move away from JSPs do you want to add a rest api?

**Comment by ryyaan2004** [comment]
I don't know, I had thought about that but I'm not sure how well that will wind up working with websockets. Although websockets in Java are a PITA and I was considering trying an implementation using message queues but I'm not sure exactly how to get started on that. What do you think?

**Comment by briankboyd** [comment]
I'd like to use rest, if you want to swap out websockets with a message queue then you better know wtf you are doing. Just kidding, if you think it would be fun I'm down.

**Comment by ryyaan2004** [comment]
rest it is, message queue is out for now
